name: Realizar una operación

on:
  push:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

  call-reusable-workflow:
    uses: ./.github/workflows/ejercicio6.yml
    with:
      valor1: 1
      valor2: 2
      operacion: '+'
