on:
  workflow_dispatch:

name: Run Azure Login without subscription
permissions:
  id-token: write
  contents: read
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Iniciar sesión en azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        allow-no-subscriptions: true
        enable-AzPSSession: true


