name: Realizar una operación

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
   
  call-reusable-workflow:
    uses: ./.github/workflows/ejercicio4.yml
    with:
      valor1: 1
      valor2: 2
      operacion: +
