name: Issue en Pull Request

on:
  pull_request:
    branches: 
      - '*'

jobs:
  generate-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install gh cli
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh
          
      - name: Run script to generate issue
        id: generate_issue
        run: |
          ./generate-issue.sh

      - name: Get issue number
        run: echo "Issue number is ${{ steps.generate_issue.outputs.issue_number }}"
