name: Realizar una operación

on:
  push:
    branches: 
      - '*'

jobs:
  call_ejercicio4:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4

      - name: Llamar a la calculadora
        uses: ./.github/workflows/ejercicio4.yml
        with:
          valor1: 1
          valor2: 2
          operacion: '+'
