name: Realizar una operación

on:
  push:
    branches: 
      - '*'

jobs:
  call_ejercicio4:
   
      
      - name: Llamar a la calculadora
        uses: ./.github/workflows/ejercicio4.yml
        with:
          valor1: 1
          valor2: 2
          operacion: '+'
